theme: jekyll-theme-midnight
markdown: GFM
include:
- boolean.md
- date.md
- false.md
- function.md
- index.md
- null.md
- number.md
- object.md
- promise.md
- regexp.md
- string.md
- true.md
- undefined.md
